# -*- coding: utf-8 -*-
"""DeS_SGAI-event-May2024_text.ipynb

Automatically generated by Colab.

# ___________________________
###  Text Classification: Sentiment Analysis (SA)
# ___________________________

#--- --- --- install and load libraries
!pip install transformers
from transformers import pipeline

#--- --- --- Transformers pipeline: 3 lines of code

pipe = pipeline(task="sentiment-analysis", model='siebert/sentiment-roberta-large-english')

text_data = ["I love you", "I hate you"] ### a vector (one-dimensional array) with 2 string values

print(pipe(text_data))

# ___________________________

# ___________________________
### Token Classification: Named-entity recognition (NER)
# ___________________________

#--- --- --- install and load libraries
!pip install transformers
from transformers import pipeline, AutoTokenizer, AutoModelForTokenClassification

#--- --- --- preliminaries
model_path = "d4data/biomedical-ner-all"

#--- --- --- Transformers pipeline: 3 lines of code

pipe = pipeline(task="ner", model= AutoModelForTokenClassification.from_pretrained(model_path),
                tokenizer= AutoTokenizer.from_pretrained(model_path))

text_data = "I have a mild headache"

print(pipe(text_data))
# ___________________________