# -*- coding: utf-8 -*-
"""pub-zoo_KGs_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXV...
"""

# ___________________________ requirements
### please, download MRCONSO.RRF from
### https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html

###--- --- --- --- --- --- --- python libraries
import re, string, os, sys
import datetime
#--- --- --- Google Colab
from google.colab import output, runtime, drive

# ___________________________ *** path to folders [ path to file MRCONSO.RRF ]
### please, store the file MRCONSO.RRF within the folder
EXP_dir = "/content/drive/MyDrive/pub-zoo_files/UMLS_2024AB/"

if (EXP_dir.startswith("/content/drive")):
  drive.mount('/content/drive')

# ______________________________________________________ MRCONSO.RRF
# ______________________________________________________ get the structured coded-data
# ___________________________ *** read MRCONSO.RRF
# ___________________________ *** and get Only codes for CUIs
def RgetMRCONSOcodesSCT(fin,finArr,finLang,finVOC,fno):
  tmp_data1 = '###' + '###'.join(finArr) + '###'
  tmp_l2 = []
  tmp_txt = ''
  tmp_data = ''
  tmp_lt = []
  tmp_str = ''
  tmp_cntTOT = 0
  tmp_cntTOT1 = 0

  with open(os.path.expanduser(fin),"r+") as tmp_f:
    for line in tmp_f:
      tmp_txt = line
      tmp_txt = tmp_txt.strip()
      if (tmp_txt.find('|') > -1):
        tmp_cntTOT += 1
        tmp_l2 = tmp_txt.split('|')
        #--- print tmp_l2[0] + '... ... ...' + tmp_l2[4]
        if (tmp_data1.find('###' + tmp_l2[0] + '###') > -1):
          if (tmp_l2[1] == finLang and tmp_l2[11] == finVOC):
            tmp_cntTOT1 += 1
            if (tmp_str == ''):
              tmp_str = '###' +  tmp_l2[13] + '###'
              tmp_data = "'" + tmp_l2[13] + "'"
            else:
              if (tmp_str.find('###' +  tmp_l2[13] + '###') == -1):
                tmp_str += tmp_l2[13] + '###'
                tmp_data += ",'" + tmp_l2[13] + "'"

  tmp_f.close()
  #--- --- --- --- ---
  print('matched...' + str(tmp_cntTOT1))
  tmp_data = '[' + tmp_data + ']'
  tmp_f1=open(os.path.expanduser(fno), "w")
  tmp_f1.write(tmp_data + "\n")
  print(tmp_data)
  tmp_f1.close()
#-------------------------------------EndFunction
# ___________________________ *** read MRCONSO.RRF
# ___________________________ *** and get information about CUIs
def RgetMRCONSOInfo(fin,finArr,finLang,finVOC,fno):
  tmp_data1 = '###' + '###'.join(finArr) + '###'
  tmp_l2 = []
  tmp_txt = ''
  tmp_data = ''
  tmp_lt = []
  tmp_str = ''
  tmp_cntTOT = 0
  tmp_cntTOT1 = 0
  tmp_eka = 0

  tmp_f1=open(os.path.expanduser(fno), "w")
  with open(os.path.expanduser(fin),"r+") as tmp_f:
    for line in tmp_f:
      tmp_txt = line
      tmp_txt = tmp_txt.strip()
      if (tmp_txt.find('|') > -1):
        tmp_cntTOT += 1
        tmp_l2 = tmp_txt.split('|')
        #--- print tmp_l2[0] + '... ... ...' + tmp_l2[4]
        if (tmp_data1.find('###' + tmp_l2[0] + '###') > -1):
            tmp_eka = 0
            if (finVOC == '' and tmp_l2[1] == finLang):
                        tmp_eka = 1
            if (tmp_l2[1] == finLang and tmp_l2[11] == finVOC and tmp_l2[12] == 'FN'):
                        tmp_eka = 1
            if (tmp_eka == 1):
                        tmp_cntTOT1 += 1
                        tmp_data = tmp_l2[0] + '###' + tmp_l2[11] + '###' + tmp_l2[13] + '###' + tmp_l2[14] + '###'
                        tmp_f1.write(tmp_data + "\n")
  #--- --- --- --- ---
  print('matched...' + str(tmp_cntTOT1))
  tmp_f1.close()
  tmp_f.close()
#-------------------------------------EndFunction
# ______________________________________________________ FHIR ValueSet Instances
# ______________________________________________________ extensional value sets
# ______________________________________________________ format: 'JSON', 'RDF', or non-normative 'JSON-LD'
# ___________________________
strTemp0 = '{ "resourceType" : "ValueSet",' + "\n"
strTemp0 += '  "status" : "draft",' + "\n"
strTemp0 += '   "expansion" : {' + "\n"
strTemp0 += '    "timestamp" : "<YYYY-MM-DD>T10:00:00Z",' + "\n"
strTemp0 += '    "contains" : [' + "\n"
strTemp0 += '<system,code,display>' + "\n"
strTemp0 += ' ]} }' + "\n"
# ___________________________
strTemp1 = '@prefix fhir: <http://hl7.org/fhir/> .' + "\n"
strTemp1 += '@prefix owl: <http://www.w3.org/2002/07/owl#> .' + "\n"
strTemp1 += '@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .' + "\n"
strTemp1 += '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .' + "\n" + "\n"
strTemp1 += '# - resource --------------------------------------------' + "\n"
strTemp1 += '[a fhir:ValueSet ;' + "\n"
strTemp1 += '  fhir:nodeRole fhir:treeRoot ;' + "\n"
strTemp1 += '  fhir:id [ fhir:v "example"] ; # ' + "\n"
strTemp1 += '  fhir:status [ fhir:v "draft"] ; # ' + "\n"
strTemp1 += '  fhir:expansion [' + "\n"
strTemp1 += '     fhir:timestamp [ fhir:v "<YYYY-MM-DD>T10:00:00Z"^^xsd:dateTime ] ;' + "\n"
strTemp1 += '     fhir:contains (' + "\n"
strTemp1 += '<system,code,display>' + "\n"
strTemp1 += ')]] . # ' + "\n"
strTemp1 += '#--------------------------------------------' + "\n"
# ___________________________
strTemp2 = '{ "@context": {' + "\n"
strTemp2 += '        "xsd": "http://www.w3.org/2001/XMLSchema#",' + "\n"
strTemp2 += '         "rdfs": "http://www.w3.org/2000/01/rdf-schema#",' + "\n"
strTemp2 += '         "owl": "http://www.w3.org/2002/07/owl#",' + "\n"
strTemp2 += '         "fhir": "http://hl7.org/fhir/",' + "\n"
strTemp2 += '          "pz": "http://pub-zoo.org/"},' + "\n"
strTemp2 += ' "@graph": [{"@id": "pz:<vsName>/ValueSet", ' + "\n"
strTemp2 += '     "@type": "fhir:ValueSet",' + "\n"
strTemp2 += '     "fhir:nodeRole": {"@id": "fhir:treeRoot"},' + "\n"
strTemp2 += '     "fhir:status": {"@value": "draft", "@type": "fhir:value"},' + "\n"
strTemp2 += '     "fhir:expansion": {"@id": "pz:<vsName>/expansion"}' + "\n"
strTemp2 += '     },{"@id": "pz:<vsName>/expansion",' + "\n"
strTemp2 += '      "fhir:timestamp": {"@value": "<YYYY-MM-DD>T10:00:00Z", "@type": "xsd:dateTime" },' + "\n"
strTemp2 += '    "@graph": [' + "\n"
strTemp2 += '<identifier,system,code,display>' + "\n"
strTemp2 += ' ]  }] }' + "\n"
# ___________________________
def RcreateFHIRvs(fnFormat,fin,fnNameVS):
	tmp_eka = 0
	if (fnFormat == 'JSON'):
		RpopTemp0(fin,EXP_dir + fnNameVS + ".json")
		tmp_eka = 1
	if (fnFormat == 'RDF'):
		RpopTemp1(fin,EXP_dir + fnNameVS + ".ttl")
		tmp_eka = 1
	if (fnFormat == 'JSON-LD'):
		RpopTemp2(fin,EXP_dir + fnNameVS + ".jsonld", fnNameVS)
		tmp_eka = 1
	if (tmp_eka == 0):
		print("something went very wrong! the formats are: 'JSON', 'RDF', or non-normative 'JSON-LD'")
	else:
		print("all done! have a nice day! :-))")
#-------------------------------------EndFunction
def RpopTemp0(fin,fno):
	tmp_f = open(os.path.expanduser(fin),"r+")
	tmp_data = tmp_f.read()
	tmp_f.close()

	tmp_l = tmp_data.split("\n")
	tmp_txt = ''
	tmp_data = ''
	tmp_lt = []
	tmp_str = ''
	tmp_cntTOT = 0

	tmp_txtA = ''
	tmp_eka = 0
	#--- --- --- --- ---
	strDateCreated = datetime.datetime.now()
	tmp_str = str(strDateCreated.year) + '-' + str(strDateCreated.strftime("%m")) + '-' + str(strDateCreated.strftime("%d"))
	tmp_txtA = strTemp0.replace('<YYYY-MM-DD>',tmp_str)
	#--- --- --- --- ---
	tmp_cnt = 0
	while tmp_cnt < len(tmp_l):
		tmp_txt = tmp_l[tmp_cnt].strip()
		if (tmp_txt.find('###') > -1):
			tmp_lt = tmp_txt.split('###')
			tmp_cntTOT += 1
			tmp_eka = 0
			if (tmp_data != ''):
				tmp_data += ',' + "\n"
			if (tmp_lt[1] == 'SNOMEDCT_US'):
				tmp_eka = 1
				tmp_data += "\t" + '{"system" : "http://snomed.info/sct", ' + "\n"
				tmp_data += "\t" + '"code" : "' + tmp_lt[2] + '", "display" : "' + tmp_lt[3]  + '"}'
			if (tmp_lt[1] == 'SNOMEDCT_VET'):
				tmp_eka = 1
				tmp_data += "\t" + '{"system" : "https://vtsl.vetmed.vt.edu/vetsct", ' + "\n"
				tmp_data += "\t" + '"code" : "' + tmp_lt[2] + '", "display" : "' + tmp_lt[3]  + '"}'
			if  (tmp_eka == 0):
				tmp_data += "\t" + '{"system" : "http://not-a-known-code-system", ' + "\n"
				tmp_data += "\t" + '"code" : "not-known-code", "display" : "' + tmp_lt[3]  + '"}'
		#---
		tmp_cnt = tmp_cnt + 1
	#--- --- --- --- ---
	###---print(str(tmp_cntTOT))

	tmp_f1=open(os.path.expanduser(fno), "w")
	tmp_txtA = tmp_txtA.replace('<system,code,display>',tmp_data)
	tmp_f1.write("\n" + tmp_txtA + "\n")

	tmp_f1.close()
#-------------------------------------EndFunction
def RpopTemp1(fin,fno):
	tmp_f = open(os.path.expanduser(fin),"r+")
	tmp_data = tmp_f.read()
	tmp_f.close()

	tmp_l = tmp_data.split("\n")
	tmp_txt = ''
	tmp_data = ''
	tmp_lt = []
	tmp_str = ''
	tmp_cntTOT = 0

	tmp_txtA = ''
	tmp_eka = 0
	#--- --- --- --- ---
	strDateCreated = datetime.datetime.now()
	tmp_str = str(strDateCreated.year) + '-' + str(strDateCreated.strftime("%m")) + '-' + str(strDateCreated.strftime("%d"))
	tmp_txtA = strTemp1.replace('<YYYY-MM-DD>',tmp_str)
	#--- --- --- --- ---
	tmp_cnt = 0
	while tmp_cnt < len(tmp_l):
		tmp_txt = tmp_l[tmp_cnt].strip()
		if (tmp_txt.find('###') > -1):
			tmp_lt = tmp_txt.split('###')
			tmp_cntTOT += 1
			tmp_eka = 0
			if (tmp_data != ''):
				tmp_data += ' [' + "\n"
			else:
				tmp_data ='      [' + "\n"
			if (tmp_lt[1] == 'SNOMEDCT_US'):
				tmp_eka = 1
				tmp_data += "\t" + 'fhir:system [ fhir:v "http://snomed.info/sct"^^xsd:anyURI ] ;' + "\n"
				tmp_data +=  "\t" + 'fhir:code [ fhir:v "'+ tmp_lt[2] + '" ] ;' + "\n"
				tmp_data += "\t" + 'fhir:display [ fhir:v "'+ tmp_lt[3] + '" ]' + "\n"
			if (tmp_lt[1] == 'SNOMEDCT_VET'):
				tmp_eka = 1
				tmp_data += "\t" + 'fhir:system [ fhir:v "https://vtsl.vetmed.vt.edu/vetsct"^^xsd:anyURI ] ;' + "\n"
				tmp_data +=  "\t" + 'fhir:code [ fhir:v "'+ tmp_lt[2] + '" ] ;' + "\n"
				tmp_data += "\t" + 'fhir:display [ fhir:v "'+ tmp_lt[3] + '" ]' + "\n"
			if  (tmp_eka == 0):
				tmp_data += "\t" + 'fhir:system [ fhir:v "http://not-a-known-code-system"^^xsd:anyURI ] ;' + "\n"
				tmp_data +=  "\t" + 'fhir:code [ fhir:v "not-known-code" ] ;' + "\n"
				tmp_data += "\t" + 'fhir:display [ fhir:v "'+ tmp_lt[3] + '" ]' + "\n"
			tmp_data += '      ]'
		#---
		tmp_cnt = tmp_cnt + 1
	#--- --- --- --- ---
	###---print(str(tmp_cntTOT))

	tmp_f1=open(os.path.expanduser(fno), "w")
	tmp_txtA = tmp_txtA.replace('<system,code,display>',tmp_data)
	tmp_f1.write("\n" + tmp_txtA + "\n")

	tmp_f1.close()
#-------------------------------------EndFunction
def RpopTemp2(fin,fno,fnStr):
	tmp_f = open(os.path.expanduser(fin),"r+")
	tmp_data = tmp_f.read()
	tmp_f.close()

	tmp_l = tmp_data.split("\n")
	tmp_txt = ''
	tmp_data = ''
	tmp_lt = []
	tmp_str = ''
	tmp_cntTOT = 0

	tmp_txtA = ''
	tmp_eka = 0
	#--- --- --- --- ---
	strDateCreated = datetime.datetime.now()
	tmp_str = str(strDateCreated.year) + '-' + str(strDateCreated.strftime("%m")) + '-' + str(strDateCreated.strftime("%d"))
	tmp_txtA = strTemp2.replace('<YYYY-MM-DD>',tmp_str)
	#--- --- --- --- ---
	tmp_txtA = tmp_txtA.replace('<vsName>',fnStr)
	#--- --- --- --- ---
	tmp_cnt = 0
	while tmp_cnt < len(tmp_l):
		tmp_txt = tmp_l[tmp_cnt].strip()
		if (tmp_txt.find('###') > -1):
			tmp_lt = tmp_txt.split('###')
			tmp_cntTOT += 1
			tmp_eka = 0
			if (tmp_data != ''):
				tmp_data += ',{' + "\n"
			else:
				tmp_data = '      {' + "\n"
			if (tmp_lt[1] == 'SNOMEDCT_US'):
				tmp_eka = 1
				tmp_data += "\t" + '"@id": "pz:' + fnStr + '/sct_' + tmp_lt[2] + '",' + "\n"
				tmp_data += "\t" + '"fhir:system":{"@value":"http://snomed.info/sct", "@type": "xsd:anyURI" },' + "\n"
				tmp_data += "\t" + '"fhir:code":{"@value":"' + tmp_lt[2]  + '", "@type": "fhir:value" },' + "\n"
				tmp_data += "\t" + '"fhir:display":{"@value":"' + tmp_lt[3] + '", "@type": "fhir:value" }' + "\n"
			if (tmp_lt[1] == 'SNOMEDCT_VET'):
				tmp_eka = 1
				tmp_data += "\t" + '"@id": "pz:' + fnStr + '/vetsct_' + tmp_lt[2] + '",' + "\n"
				tmp_data += "\t" + '"fhir:system":{"@value":"https://vtsl.vetmed.vt.edu/vetsct", "@type": "xsd:anyURI" },' + "\n"
				tmp_data += "\t" + '"fhir:code":{"@value":"' + tmp_lt[2]  + '", "@type": "fhir:value" },' + "\n"
				tmp_data += "\t" + '"fhir:display":{"@value":"' + tmp_lt[3] + '", "@type": "fhir:value" }' + "\n"
			if  (tmp_eka == 0):
				tmp_data += "\t" + '"@id": "pz:' + fnStr + '/not-known-code_' + tmp_lt[3].replace(' ', '_') + '",' + "\n"
				tmp_data += "\t" + '"fhir:system":{"@value":"http://not-a-known-code-system", "@type": "xsd:anyURI" },' + "\n"
				tmp_data += "\t" + '"fhir:code":{"@value":"not-known-code", "@type": "fhir:value" },' + "\n"
				tmp_data += "\t" + '"fhir:display":{"@value":"' + tmp_lt[3] + '", "@type": "fhir:value" }' + "\n"
			tmp_data += '      }'
		#---
		tmp_cnt = tmp_cnt + 1
	#--- --- --- --- ---
	###---print(str(tmp_cntTOT))

	tmp_f1=open(os.path.expanduser(fno), "w")
	tmp_txtA = tmp_txtA.replace('<identifier,system,code,display>',tmp_data)
	tmp_f1.write("\n" + tmp_txtA + "\n")

	tmp_f1.close()
#-------------------------------------EndFunction
# ______________________________________________________ nanoPublications
# ______________________________________________________ format: JSON-LD
# ___________________________
strTemp3 = '{    ' + "\n"
strTemp3 += '   "@context": {' + "\n"
strTemp3 += ' 	"np": "http://www.nanopub.org/nschema#",' + "\n"
strTemp3 += ' 	"dct": "http://purl.org/dc/terms/",' + "\n"
strTemp3 += ' 	"xsd": "http://www.w3.org/2001/XMLSchema#",' + "\n"
strTemp3 += ' 	"rdfs": "http://www.w3.org/2000/01/rdf-schema#",' + "\n"
strTemp3 += ' 	"owl": "http://www.w3.org/2002/07/owl#",' + "\n"
strTemp3 += ' 	"skos": "http://www.w3.org/2004/02/skos/core#",' + "\n"
strTemp3 += ' 	"prov": "http://www.w3.org/ns/prov-o#",' + "\n"
strTemp3 += ' 	"obo": "http://purl.obolibrary.org/obo/",' + "\n"
strTemp3 += ' 	"sio": "http://semanticscience.org/resource/",' + "\n"
strTemp3 += ' 	"umls": "https://uts.nlm.nih.gov/uts/umls",' + "\n"
strTemp3 += ' 	"orcid": "http://orcid.org/",' + "\n"
strTemp3 += ' 	"pz": "http://pub-zoo.org/"' + "\n"
strTemp3 += '     },' + "\n"
strTemp3 += '     "@graph": [{' + "\n"
strTemp3 += ' 	"@id": "pz:pub<yearQ>/<disease_Name>/Head",' + "\n"
strTemp3 += ' 	 "@graph": [{"@id": "pz:pub<yearQ>/<disease_Name>/",' + "\n"
strTemp3 += ' 	"np:hasPublicationInfo": {"@id": "pz:pub<yearQ>/pubinfo"},' + "\n"
strTemp3 += ' 	"np:hasProvenance": {"@id": "pz:pub<yearQ>/<disease_Name>/provenance"},' + "\n"
strTemp3 += ' 	"np:hasAssertion": { "@id": "pz:pub<yearQ>/<disease_Name>/assertion"},' + "\n"
strTemp3 += ' 	"@type": "np:Nanopublication"}]' + "\n"
strTemp3 += ' 	},{' + "\n"
strTemp3 += ' 	"@id": "pz:pub<yearQ>/<disease_Name>/assertion",' + "\n"
strTemp3 += ' 	"@graph": [{"@id": "umls:<disease_CUI>","sio:SIO_001403": {"@id": "umls:<related_CUI>"} },' + "\n"
strTemp3 += ' 	{"@id": "umls:C0034362","skos:hiddenLabel": [<<terms/expressions>>] }]' + "\n"
strTemp3 += '       },{' + "\n"
strTemp3 += ' 	    "@id": "pz:pub<yearQ>/<disease_Name>/provenance",' + "\n"
strTemp3 += '             "@graph": [{ "@id": "pz:pub<yearQ>/<disease_Name>/assertion",' + "\n"
strTemp3 += '             "prov:value": { "@value": "<paragraph>" ,"@type": "xsd:string" },' + "\n"
strTemp3 += '             "prov:wasQuotedFrom": {"@id": "pz:pub<yearQ>/pubinfo"},' + "\n"
strTemp3 += ' 	     "obo:RO_0002558": {"@id": "obo:ECO_0000218"} }]' + "\n"
strTemp3 += '     },{' + "\n"
strTemp3 += ' 	"@id": "pz:pub<yearQ>/pubinfo",' + "\n"
strTemp3 += ' 	"@graph": [{"@id": "pz:pub<yearQ>/",' + "\n"
strTemp3 += '  "dct:creator": {"@id": "orcid:<ORCID>"},' + "\n"
strTemp3 += '  "dct:created": {"@value": "<YYYY-MM-DD>T10:00:00Z","@type": "xsd:dateTime" },' + "\n"
strTemp3 += ' 	"dct:title": {"@value": "<pub_Title>","@type": "xsd:string" },' + "\n"
strTemp3 += ' 	"dct:issued": {"@value": "<pub_DateIssued>","@type": "xsd:gYearMonth" },' + "\n"
strTemp3 += ' 	"dct:identifier": {"@id": "<pub_Identifier>"} }] ' + "\n"
strTemp3 += ' }]}' + "\n"
# ___________________________
# ___________________________
def RcreateNanoPub(fin,strORCID):
	tmp_f = open(os.path.expanduser(fin),"r+")
	tmp_data = tmp_f.read()
	tmp_f.close()

	fno = fin.replace('.txt', '_np.jsonld')

	tmp_l = tmp_data.split("\n")
	tmp_txt = ''
	tmp_data = ''
	tmp_lt = []
	tmp_str = ''
	tmp_cntTOT = 0

	tmp_txtA = ''
	tmp_eka = 0
	#--- --- --- --- ---
	strDateCreated = datetime.datetime.now()
	tmp_str = str(strDateCreated.year) + '-' + str(strDateCreated.strftime("%m")) + '-' + str(strDateCreated.strftime("%d"))
	tmp_txtA = strTemp3.replace('<YYYY-MM-DD>',tmp_str)
	#--- --- --- --- ---
	tmp_txtA = tmp_txtA.replace('<ORCID>',strORCID)
	#--- --- --- --- ---
	#--- --- --- --- --- read line
	tmp_cnt = 0
	while tmp_cnt < len(tmp_l):
		tmp_txt = tmp_l[tmp_cnt].strip()
		if (tmp_txt.find('###') > -1):
			tmp_lt = tmp_txt.split('###')
			tmp_cntTOT += 1
			tmp_txtA = tmp_txtA.replace('<yearQ>',tmp_lt[0])
			tmp_txtA = tmp_txtA.replace('<disease_Name>',tmp_lt[1])
			tmp_txtA = tmp_txtA.replace('<disease_CUI>',tmp_lt[2])
			tmp_txtA = tmp_txtA.replace('<related_CUI>',tmp_lt[3])
			tmp_txtA = tmp_txtA.replace('<<terms/expressions>>',tmp_lt[4])
			tmp_txtA = tmp_txtA.replace('<paragraph>',tmp_lt[5])
			tmp_txtA = tmp_txtA.replace('<pub_Title>',tmp_lt[6])
			tmp_txtA = tmp_txtA.replace('<pub_DateIssued>',tmp_lt[7])
			tmp_txtA = tmp_txtA.replace('<pub_Identifier>',tmp_lt[8])

			if (tmp_cntTOT == 1):
				tmp_cnt = len(tmp_l)
		#---
		tmp_cnt = tmp_cnt + 1
	#--- --- --- --- ---
	###---print(str(tmp_cntTOT))
	print("all done! have a nice day! :-))")

	tmp_f1=open(os.path.expanduser(fno), "w")
	tmp_f1.write("\n" + tmp_txtA + "\n")
	tmp_f1.close()
#-------------------------------------EndFunction

###--- --- --- excute the 1 line below [ get Only the codes from a VOC source] [ useful for creating an ontology signature (set of entities) ]
RgetMRCONSOcodesSCT(EXP_dir + 'MRCONSO_sample.RRF', ['C0034362','C0010240'], 'ENG', 'SNOMEDCT_US', EXP_dir + 'codes2CUIs-Qfever__pub-zoo.txt')

###--- --- --- excute the 1 line below [ get information about CUIs ][ any source vocabularies represented in the UMLS ]
RgetMRCONSOInfo(EXP_dir + 'MRCONSO_sample.RRF', ['C0034362','C0010240'], 'ENG', '', EXP_dir + 'info2CUIs-Qfever-EnglishUMLS__pub-zoo.txt')

###--- --- --- excute the 1 line below [ get information about CUIs ][ this information is needed for creating value sets ]
RgetMRCONSOInfo(EXP_dir + 'MRCONSO_sample.RRF', ['C0034362','C0010240'], 'ENG', 'SNOMEDCT_US', EXP_dir + 'info2CUIs-Qfever__pub-zoo.txt')

###--- --- --- excute the 1 line below to create a FHIR ValueSet instance in JSON [ the input file was created with RgetMRCONSOInfo() ]
RcreateFHIRvs('JSON', EXP_dir + 'info2CUIs-Qfever__pub-zoo.txt', 'vsQfever')

###--- --- --- excute the 1 line below to create a FHIR ValueSet instance in RDF Turtle [ the input file was created with RgetMRCONSOInfo() ]
RcreateFHIRvs('RDF', EXP_dir + 'info2CUIs-Qfever__pub-zoo.txt', 'vsQfever')

###--- --- --- excute the 1 line below to create a FHIR ValueSet instance in non-normative JSON-LD [ the input file was created with RgetMRCONSOInfo() ]
RcreateFHIRvs('JSON-LD', EXP_dir + 'info2CUIs-Qfever__pub-zoo.txt', 'vsQfever')

###--- --- --- excute the 1 line below to create a nanoPublication in JSON-LD [ a dummy ORCID is used to identify the creator of the nanoPublication ]
RcreateNanoPub(EXP_dir + '5_2024Q2.txt','0000-0000-0000-0001')