# -*- coding: utf-8 -*-
"""pub-zoo_MRCONSO.ipynb

Automatically generated by Colab.

"""

# ___________________________ requirements

### Names, Synonyms, Terms, Term Types, Codes

### download MRCONSO.RRF from
### https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html

###--- --- --- --- --- --- --- python libraries
import re, string, os, sys
#--- --- --- Google Colab
from google.colab import output, runtime, drive

# ___________________________ *** path to folders [ path to file MRCONSO.RRF ]
EXP_dir = "/content/drive/MyDrive/pub-zoo_files/UMLS_2024AB/"

if (EXP_dir.startswith("/content/drive")):
  drive.mount('/content/drive')

# ___________________________ *** read MRCONSO.RRF
# ___________________________ *** and get information about CUIs
def RgetMRCONSOv1(fin,finArr,finLang,finVOC,fno):
  tmp_data1 = '###' + '###'.join(finArr) + '###'
  tmp_l2 = []
  tmp_txt = ''
  tmp_data = ''
  tmp_lt = []
  tmp_str = ''
  tmp_cntTOT = 0
  tmp_cntTOT1 = 0

  tmp_f1=open(os.path.expanduser(fno), "w")
  with open(os.path.expanduser(fin),"r+") as tmp_f:
    for line in tmp_f:
      tmp_txt = line
      tmp_txt = tmp_txt.strip()
      if (tmp_txt.find('|') > -1):
        tmp_cntTOT += 1
        tmp_l2 = tmp_txt.split('|')
        #--- print tmp_l2[0] + '... ... ...' + tmp_l2[4]
        if (tmp_data1.find('###' + tmp_l2[0] + '###') > -1):
          if (tmp_l2[1] == finLang and tmp_l2[11] == finVOC):
            tmp_cntTOT1 += 1
            tmp_data = tmp_l2[0] + '###' + tmp_l2[7] + '###' + tmp_l2[11] + '###' + tmp_l2[12] + '###'
            tmp_data += tmp_l2[13] + '###' + tmp_l2[14] + '###' + tmp_l2[15] + '###' + tmp_l2[16] + '###' + str(tmp_l2[14].lower()).strip()
            tmp_f1.write(tmp_data + "\n")
  #--- --- --- --- ---
  print('matched...' + str(tmp_cntTOT1))
  tmp_f1.close()
  tmp_f.close()
#-------------------------------------EndFunction
# ___________________________
# ___________________________ uncomment and excute the 1 line below

### RgetMRCONSOv1(EXP_dir + 'MRCONSO_sample.RRF', ['C0034362','C0010240'], 'ENG', 'SNOMEDCT_US', EXP_dir + 'info2CUIs-SCT__pub-zoo.txt')
